name: makefile-workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: [ubuntu-18.04]
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --no-cache-dir poetry==1.0.9
          poetry config virtualenvs.create false
          poetry install --no-interaction
      - name: Check linters
        run: |
          make lint
      - name: Run tests
        run: |
          make tests
